# Generated by Django 5.0.6 on 2024-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='character',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
