# Generated by Django 5.0.6 on 2024-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
