# Generated by Django 5.0.6 on 2024-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_actor_image_url_alter_movie_director_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='character',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
