# Generated by Django 5.0.6 on 2024-07-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_actor_name_alter_movie_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='character',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
