# Generated by Django 5.0.6 on 2024-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_actor_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='character',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
